services:
  - type: web
    name: finbot-v3
    env: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: npm ci && npx vite build
    startCommand: node scripts/setup-database.js && npx tsx server/index.ts
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false

