name: Backup Swagger UI Express

on:
  schedule:
    - cron: '0 17 * * *' # Run every day at 5 PM
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  POSTGRES_VERSION: '15'

jobs:
  backup-swagger-ui-express:
    name: Backup Swagger UI Express
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Backup swagger-ui-express
        run: |
          echo "Backing up swagger-ui-express..."
          # Add swagger-ui-express backup logic here
          echo "Swagger UI Express backup completed ✅"

  backup-ts-node:
    name: Backup TS Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Backup ts-node
        run: |
          echo "Backing up ts-node..."
          # Add ts-node backup logic here
          echo "TS Node backup completed ✅"
