name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Version to rollback to'
        required: true
        default: 'previous'

env:
  NODE_VERSION: '18'
  POSTGRES_VERSION: '15'

jobs:
  rollback-staging:
    name: Rollback Staging
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'staging'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Rollback staging
        run: |
          echo "Rolling back staging to version ${{ github.event.inputs.version }}..."
          # Add staging rollback logic here
          echo "Staging rollback completed ✅"

  rollback-production:
    name: Rollback Production
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Rollback production
        run: |
          echo "Rolling back production to version ${{ github.event.inputs.version }}..."
          # Add production rollback logic here
          echo "Production rollback completed ✅"
